on:
  push:
    branches:
      - main
      - wasm
  pull_request:
    branches:
      - main
      - wasm

name: WasmBuild
jobs:
  wasm:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set GOOS env 
      run: echo GOOS=js >> ${GITHUB_ENV}
    - name: Set GOARCH env 
      run: echo GOARCH=wasm >> ${GITHUB_ENV}
    - name: Set GIT_COMMIT env 
      run: echo GIT_COMMIT=$(git rev-parse --short HEAD) >> ${GITHUB_ENV}
    - name: Build
      run: go build -ldflags "-X github.com/rumsystem/quorum/internal/pkg/utils.GitCommit=$GIT_COMMIT" -o lib.wasm cmd/wasm/lib.go